export const COLOURS = {
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  blue: '#0043F9',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
};

export const sliderData = [
  {
    title: 'First Game',
    image: require('../assets/images/homescreen/game-1.jpeg'),
  },
  {
    title: 'Second Game',
    image: require('../assets/images/homescreen/game-2.jpeg'),
  },
  {
    title: 'Third Game',
    image: require('../assets/images/homescreen/game-3.png'),
  },
];

export const mostBoughtGames = [
  {
    poster: require('../assets/images/fortnite.webp'),
    title: 'Fortnite',
    subtitle: 'Epic Games',
    isFree: 'No',
    price: 25.99,
    id: '4',
    productImageList: [
      require('../assets/images/fortnite.webp'),
      require('../assets/images/fortnite.webp'),
      require('../assets/images/fortnite.webp'),
    ],
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Spider-Man: Miles Morales',
    subtitle: 'Marvel',
    isFree: 'No',
    price: 29.99,
    id: '3',
    productImageList: [
      require('../assets/images/miles-morales.webp'),
      require('../assets/images/miles-morales.webp'),
      require('../assets/images/miles-morales.webp'),
    ],
  },
  {
    poster: require('../assets/images/asphalt-9.jpeg'),
    title: 'Asphalt 9',
    subtitle: 'Gameloft',
    isFree: 'No',
    price: 15.99,
    id: '2',
    productImageList: [
      require('../assets/images/asphalt-9.jpeg'),
      require('../assets/images/asphalt-9.jpeg'),
      require('../assets/images/asphalt-9.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Pokémon Unite',
    subtitle: 'The Pokémon Company',
    isFree: 'No',
    price: 20.99,
    id: '7',
    productImageList: [
      require('../assets/images/pokemon-unite.jpeg'),
      require('../assets/images/pokemon-unite.jpeg'),
      require('../assets/images/pokemon-unite.jpeg'),
    ],
  },
];

export const paidGames = [
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Spider-Man',
    subtitle: 'Marvel',
    isFree: 'No',
    price: 25.99,
    id: '1',
    productImageList: [
      require('../assets/images/spiderman.webp'),
      require('../assets/images/spiderman.webp'),
      require('../assets/images/spiderman.webp'),
    ],
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Battlefield 2042',
    subtitle: 'EA',
    isFree: 'No',
    price: 19.99,
    id: '2',
    productImageList: [
      require('../assets/images/battlefield-2042.webp'),
      require('../assets/images/battlefield-2042.webp'),
      require('../assets/images/battlefield-2042.webp'),
    ],
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Spider-Man: Miles Morales',
    subtitle: 'Marvel',
    isFree: 'No',
    price: 29.99,
    id: '3',
    productImageList: [
      require('../assets/images/miles-morales.webp'),
      require('../assets/images/miles-morales.webp'),
      require('../assets/images/miles-morales.webp'),
    ],
  },
  {
    poster: require('../assets/images/halo-infinite.jpeg'),
    title: 'Halo Infinite',
    subtitle: 'Xbox Game',
    isFree: 'No',
    price: 24.99,
    id: '4',
    productImageList: [
      require('../assets/images/halo-infinite.jpeg'),
      require('../assets/images/halo-infinite.jpeg'),
      require('../assets/images/halo-infinite.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/FarCry6.png'),
    title: 'Far Cry 6',
    subtitle: 'Ubisoft',
    isFree: 'No',
    price: 15.99,
    id: '5',
    productImageList: [
      require('../assets/images/FarCry6.png'),
      require('../assets/images/FarCry6.png'),
      require('../assets/images/FarCry6.png'),
    ],
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'God of War: Ragnarok',
    subtitle: 'Sony',
    isFree: 'No',
    price: 25.99,
    id: '6',
    productImageList: [
      require('../assets/images/god-of-war.jpeg'),
      require('../assets/images/god-of-war.jpeg'),
      require('../assets/images/god-of-war.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Pokémon Unite',
    subtitle: 'The Pokémon Company',
    isFree: 'No',
    price: 20.99,
    id: '7',
    productImageList: [
      require('../assets/images/pokemon-unite.jpeg'),
      require('../assets/images/pokemon-unite.jpeg'),
      require('../assets/images/pokemon-unite.jpeg'),
    ],
  },
];

export const freeGames = [
  {
    poster: require('../assets/images/Altos-Odyssey.jpeg'),
    title: 'Altos Odyssey',
    subtitle: 'Noodlecake Studios',
    isFree: 'No',
    price: 15.99,
    id: '1',
    productImageList: [
      require('../assets/images/Altos-Odyssey.jpeg'),
      require('../assets/images/Altos-Odyssey.jpeg'),
      require('../assets/images/Altos-Odyssey.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/asphalt-9.jpeg'),
    title: 'Asphalt 9',
    subtitle: 'Gameloft',
    isFree: 'No',
    price: 15.99,
    id: '2',
    productImageList: [
      require('../assets/images/asphalt-9.jpeg'),
      require('../assets/images/asphalt-9.jpeg'),
      require('../assets/images/asphalt-9.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/genshin-impact.jpeg'),
    title: 'Genshin Impact',
    subtitle: 'miHoYo',
    isFree: 'No',
    price: 17.99,
    id: '3',
    productImageList: [
      require('../assets/images/genshin-impact.jpeg'),
      require('../assets/images/genshin-impact.jpeg'),
      require('../assets/images/genshin-impact.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/fortnite.webp'),
    title: 'Fortnite',
    subtitle: 'Epic Games',
    isFree: 'No',
    price: 25.99,
    id: '4',
    productImageList: [
      require('../assets/images/fortnite.webp'),
      require('../assets/images/fortnite.webp'),
      require('../assets/images/fortnite.webp'),
    ],
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Pokémon Unite',
    subtitle: 'The Pokémon Company',
    isFree: 'No',
    price: 20.99,
    id: '5',
    productImageList: [
      require('../assets/images/pokemon-unite.jpeg'),
      require('../assets/images/pokemon-unite.jpeg'),
      require('../assets/images/pokemon-unite.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/diablo-4.jpeg'),
    title: 'Diablo 4',
    subtitle: 'Blizzard Entertainment',
    isFree: 'No',
    price: 10.99,
    id: '6',
    productImageList: [
      require('../assets/images/diablo-4.jpeg'),
      require('../assets/images/diablo-4.jpeg'),
      require('../assets/images/diablo-4.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/halo-infinite.jpeg'),
    title: 'Halo Infinite',
    subtitle: 'Xbox Game',
    isFree: 'No',
    price: 24.99,
    id: '7',
    productImageList: [
      require('../assets/images/halo-infinite.jpeg'),
      require('../assets/images/halo-infinite.jpeg'),
      require('../assets/images/halo-infinite.jpeg'),
    ],
  },
];

export const toprated = [
  {
    poster: require('../assets/images/FarCry6.png'),
    title: 'Far Cry 6',
    subtitle: 'Ubisoft',
    isFree: 'No',
    price: 15.99,
    id: '1',
    productImageList: [
      require('../assets/images/FarCry6.png'),
      require('../assets/images/FarCry6.png'),
      require('../assets/images/FarCry6.png'),
    ],
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Spider-Man: Miles Morales',
    subtitle: 'Marvel',
    isFree: 'No',
    price: 29.99,
    id: '2',
    productImageList: [
      require('../assets/images/miles-morales.webp'),
      require('../assets/images/miles-morales.webp'),
      require('../assets/images/miles-morales.webp'),
    ],
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Battlefield 2042',
    subtitle: 'EA',
    isFree: 'No',
    price: 19.99,
    id: '3',
    productImageList: [
      require('../assets/images/battlefield-2042.webp'),
      require('../assets/images/battlefield-2042.webp'),
      require('../assets/images/battlefield-2042.webp'),
    ],
  },
  {
    poster: require('../assets/images/genshin-impact.jpeg'),
    title: 'Genshin Impact',
    subtitle: 'miHoYo',
    isFree: 'No',
    price: 17.99,
    id: '4',
    productImageList: [
      require('../assets/images/genshin-impact.jpeg'),
      require('../assets/images/genshin-impact.jpeg'),
      require('../assets/images/genshin-impact.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/fortnite.webp'),
    title: 'Fortnite',
    subtitle: 'Epic Games',
    isFree: 'No',
    price: 25.99,
    id: '5',
    productImageList: [
      require('../assets/images/fortnite.webp'),
      require('../assets/images/fortnite.webp'),
      require('../assets/images/fortnite.webp'),
    ],
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Pokémon Unite',
    subtitle: 'The Pokémon Company',
    isFree: 'No',
    price: 20.99,
    id: '6',
    productImageList: [
      require('../assets/images/pokemon-unite.jpeg'),
      require('../assets/images/pokemon-unite.jpeg'),
      require('../assets/images/pokemon-unite.jpeg'),
    ],
  },
  {
    poster: require('../assets/images/halo-infinite.jpeg'),
    title: 'Halo Infinite',
    subtitle: 'Xbox Game',
    isFree: 'No',
    price: 24.99,
    id: '7',
    productImageList: [
      require('../assets/images/halo-infinite.jpeg'),
      require('../assets/images/halo-infinite.jpeg'),
      require('../assets/images/halo-infinite.jpeg'),
    ],
  },
];